themeName: DarkGreen
temperatureSetDefaultColor: 0xFF000099
defaultSetpoint: 18
minSetpoint: 7
maxSetpoint: 30
thermostatResolution: 0.5
# MQTT topics to use to communicate with the heating control server
mqtt:
  SendTopic: 'heatingcontrol/command'
  onIsAliveTopic: 'heatingcontrol/serverdata/is_alive'
  onResponseTopic: 'heatingcontrol/on_cmd_response'
  onSchedulerTopic: 'heatingcontrol/serverdata/on_scheduler'
  onDevicesTopic: 'heatingcontrol/serverdata/on_devices'
  onEntitiesTopic: 'heatingcontrol/serverdata/on_entities'
  onDeviceChangeTopic: 'heatingcontrol/serverdata/devices/#'
  isAliveTimeout: 8
  # normal: 1883, secure: 8883
  # websocket: 1884, secure: 8884
  port: 8884
  secure: true

  # For the following parameters, you can :
  # 1) Set them in secrets.yaml (under mqtt tag)
  # 2) Set them in the settingz page of the running application
  # => Prefer #2 to insure secured storage of these values since secrets.yaml will be accessible in the target storage !
  brokerAddress: ''
  user: ''
  password: ''